version: "3.8"
services:
  netbase-quid-offsite-test-use-typescript:
    build:
      context: .
      target: BUILD_OPTIMIZED_SERVER
    image: karta0989006/netbase-quid-offsite-test-use-typescript
    ports:
      - 5000:5000
    # command: ["npm", "run", "dev"]
    command: ["node", "dist/index.js"]